#---
#Name: mysite
#After:
#  - 'framework/*'
#  - 'cms/*'
#---
#SilverStripe\View\SSViewer:
#  theme: simple
#SilverStripe\Dev\Debug:
#  friendly_error_httpcode: true
SilverStripe\ORM\DatabaseAdmin:
  classname_value_remapping:
    Player: SS\Test\Polymorphic\Player
    Team: SS\Test\Polymorphic\Team
    HockeyTeam: SS\Test\Polymorphic\HockeyTeam
    ZFan: SS\Test\Polymorphic\ZFan
